[package]
name = "live2d_mini"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
live2d_mini_sys={path="../live2d_mini_sys"}
