[package]
name = "live2d_mini_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
live2d_mini_sys = { path = "../live2d_mini_sys" }
live2d_mini = {path = "../live2d_mini"}

miniquad = "0.3.15"
image = "0.24.5"
serde_json = "1.0.93"
serde = { version = "1.0.152", features = ["derive"] }
